name: CI Notifier

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run fake test (intencional error)
        run: |
          echo "Simulando error de prueba..."
          exit 1

      - name: Notificar a Discord si falla
        if: failure()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content": "❌ El CI falló en `${{ github.repository }}` (commit `${{ github.sha }}`) por `${{ github.actor }}`."}' \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
